language: node_js
node_js:
- '0.12'
dist: trusty

services:
  - docker

script:
- "./workspace-init"
- "./makebuild"

before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
- provider: script
  skip_cleanup: true
  script: docker build -t cha87de/easycom:master . ; docker push cha87de/easycom:master
  on:
    branch: master
- provider: releases
  api_key:
    secure: S0baDwe8x5+cSt3poiv5vFBl5zYaZXWvPV+8rRDsZgACDZKZuXZRhOXL9Rmx/6iD7d8576jn1D0OXvxSFgg27jCZdY9QsKQW6/Dvxw7zRPz4DEI6gAmazi9vY/NvRNxXWgEhullw+PodxJ1F958SaAqh5aVZk6II2Gbx/phsinr5j89yu1PhBoT4Mp6nUtIWlu9elvDiH5UdTfnOgSDOPgXK6IPUknwVU85rrF97WebpK/YP2HF3QdB9jqtH2iNelkKvZ7Rex0jX0M3J5ZeEazsQT4vkWRn4yEbHEPeNR295qzYdOQUDpmwc311y2QbGLUGIvV6yh8U5by5wgSJLg5qR37S7K4kkwCxc7Xa0Bq8l4JzELwz6xG2/6bPUfY4diDzflXD+6u0/09BnViucOk0FOJRXV5FZ1iGPhKP0AmVEHSaTPT5nK1NWsFCpHYU1TtkKI6qmD//cRyZK9Z9FIGs4QBtq/9JmbzcuyDC46Xhwg812eNje31tTNho5mqQ75R5GWY3kmcx90fj946gPvgFDWnrvd3M/AY3nZvEudX0KJ4gO+++dBkJEO1Gd1UKenukCCv/6p/96ttKZ/fQJGJhmBkm0ASqKla8d1oDOex19OwCdSujdsAIr4PGn9VZ5Y0F28gyDamcSv40aXFW5Sx4tDKTKbxvC39Yx2qm+g3Q=
  file: easycom.tgz
  skip_cleanup: true
  on:
    repo: cha87de/easycom
    tags: true
- provider: script
  skip_cleanup: true
  script: docker build -t cha87de/easycom:latest . ; docker push cha87de/easycom:latest ; docker tag cha87de/easycom:latest cha87de/easycom:$TRAVIS_TAG ; docker push cha87de/easycom:$TRAVIS_TAG
  on:
    repo: cha87de/easycom
    tags: true
