#!/bin/bash

################################################
# init easycom:
################################################

echo "Prepare storage if not set"
(
	cd  /var/www/html/easycom-phpbackend/

	# place default database, if empty
	if [[ ! -f _data/management.db ]]; then
	    cp _data-skel/management.db _data/management.db
	fi

	# place default latex template, if empty
	if [[ ! -f _data/invoicing/template.tex ]]; then
	    cp -R _data-skel/invoicing/ _data/invoicing
	fi

	chown www-data _data -R
)

echo "Set password from ENV"
(
	htpasswd -cb /etc/apache2/.htpasswd $HTUSER $HTPASS
)

################################################
# copy of original docker image:
################################################

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"