#!/bin/bash

cd  /var/www/html/easycom-phpbackend/

# place default database, if empty
if [[ ! -f _data/management.db ]]; then
    cp _data-skel/management.db _data/management.db
fi

# place default latex template, if empty
if [[ ! -f _data/invoicing/template.tex ]]; then
    cp -R _data-skel/invoicing/ _data/invoicing
fi


################################################
# copy of original docker image:

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"