#!/bin/bash

# download extjs
if [[ ! -d ext-6.2.0 ]]; then
	wget http://cdn.sencha.com/ext/gpl/ext-6.2.0-gpl.zip
	unzip -q ext-6.2.0-gpl.zip
fi

# install sencha command
if [[ ! command -v sencha ]]; then
	wget http://cdn.sencha.com/cmd/6.2.0/no-jre/SenchaCmd-6.2.0-linux-amd64.sh.zip
	unzip -q SenchaCmd-6.2.0-linux-amd64.sh.zip
	chmod +x SenchaCmd-6.2.0.103-linux-amd64.sh
	./SenchaCmd-6.2.0.103-linux-amd64.sh -q
	export PATH=~/bin/Sencha/Cmd/6.2.0.103:$PATH
fi

# create sencha ext workspace
if [[ ! -f workspace.json ]]; then
	sencha generate workspace .
	mv workspace.json workspace.json.tmp
	head -n -2 workspace.json.tmp > workspace.json
	rm workspace.json.tmp
	echo -e "    },
	\"frameworks\": {
		\"ext\": {
			\"path\":\"./ext-6.2.0\",
			\"version\":\"6.2.0\"
			}
		}
	}" >> workspace.json
	
	# install app in new workspace
	cd easycom-webui
	sencha app install
	cd ..
fi

echo "Initialization finished. Next step, run './workspace-run-dev'"
